mcode/request-generator

package-lock.json
package.json
src/components/App.js
src/components/Auth/Alert.jsx
src/components/Auth/Login.jsx
src/components/Auth/styles.jsx
src/components/Dashboard/Dashboard.jsx
src/components/Dashboard/DashboardElement.jsx
src/components/Dashboard/styles.jsx
src/containers/PatientPortal.jsx
src/containers/styles/styles.jsx
src/containers/styles/theme.jsx

Make sure to use the patient-portal branch of the test-ehr with this.  You will have to load the keycloak json to get it to work.
This PR adds a patient portal endpoint at `/patient-portal`, a login UI and a viewer for the returned QuestionnaireResponses.   Changes to the keycloak server allow return of information like the patientId through the accessToken.  Using that, the patient portal allows users to login and then returns a list of only their in-progress QuestionnaireResponses.  
To test, ensure jonsnow has some in-progress QuestionnaireResponses in the EHR, then login as jonsnow in the patient-portal.  You should see the QuestionnaireResponses appear in the UI.  Future tasks will implement integration with DTR and interaction with the information, the goal of this task is simply …

create patient portal endpoint & ui

---

src/components/RequestBox/RequestBox.js
src/properties.json
src/util/buildScript.2017071.js
src/util/buildScript.2022071.js

Update the NCPDP SCRIPT NewRx message sent to PIMS to include the necessary required fields. The code has been split out into a separate file, and another version for the currently used version of SCRIPT (2017071) has been created as well. These changes should be tested with the changes to the test-ehr on the required-fields branch.
[REMS-309](https://jira.mitre.org/browse/REMS-309)

[REMS-309] Update NCPDP SCRIPT NewRx

---

.github/workflows/docker-cd-dev.yml
.github/workflows/docker-cd.yml
.github/workflows/docker-tag-cd.yml
.vscode/launch.json
Dockerfile
Dockerfile.dev
README.md

REMS -> rems-admin 
crd-request-generator -> request-generator 
- Updated documentation 
- Updated paths for new repo names path in docker files and files that reference it 
**Need to update Docker Hub to reflect correct repository path**
No action is needed unless you are running dockerized version. Operations targeting the previous location will continue to function as if made on the new location. If you want you can remove these repositories and reclone them to avoid confusion:
`git clone https://github.com/mcode/request-generator.git%60`
`git clone https://github.com/mcode/rems-admin.git`
Or just update local clones to point to the new directory url (not needed but good practice to avoid confusion. 
In `/REMS`
`git remote set-url origin https://github.com/mcode/rems-admin.git` 
In …

Update Repo Naming (2/3)

---

src/components/ConsoleBox/ConsoleBox.js
src/components/ConsoleBox/consoleBox.css
src/components/RequestBox/RequestBox.js
src/components/RequestBox/request.css
src/containers/RequestBuilder.js
src/index.css

Updates to the patient select button, hiding fields and buttons when no patient is selected, added in a 'empty' state vs N/A when there is no data, rename some of the button names, disabled the 'open in-progress forms' button if no form is selected, and change button for open developer console instead of +.
To test:
Load the request generator, see all visual changes on initial load when no patient is selected. Select a patient without a medication. See the buttons and information show, with the appropriate buttons disabled. Then load the patient with medication and see the other buttons enabled as well as some more information filled in. Then go through and get an in progress form. Open up an in progress form and see the 'open in-progress form' button is enabled. …

504 & 505 patient select UI updates and hiding empty state

---

src/components/DisplayBox/DisplayBox.js
src/containers/RequestBuilder.js

Update the request generator UI to not show the cards area when the application launches and there are no cards to show. Then when there is a return from the CDS Hook call, show the number of cards above any cards to display. If there are none, "Notification Cards (0)" will display.
https://jira.mitre.org/browse/REMS-508

Change how the cards UI is displayed when there are none.

---

.env
.eslintignore
.prettierignore
build.js
package-lock.json
package.json
src/components/App.js

Introduces rewire module to allow modifying the production build.  Production build is adjusted to be un-minified, minified version does not work.  Also adds deploy task to deploy to build to github gh_pages branch. 

Deploy updates

---

.env
src/components/App.js
src/components/ConsoleBox/ConsoleBox.js
src/components/Dashboard/DashboardElement.jsx
src/components/DisplayBox/DisplayBox.js
src/components/RequestBox/RequestBox.js
src/components/SMARTBox/PatientBox.js
src/containers/Index.jsx
src/containers/Launch.jsx
src/containers/RequestBuilder.js
src/util/util.js

Makes the request generator a SMART app.  When launching through a launcher or sandbox, use `/launch`, otherwise accessing the page will initiate a standalone launch against whatever EHR is in the env variables.  You can use the reconnect button to connect to a different EHR by changing the setting after loading.

add smart launch

---

src/components/App.js
src/components/RequestBox/RequestBox.js
src/containers/Launch.jsx
src/containers/RequestBuilder.js

Fixing issue where when using the HashRouter on GH Pages the values for the smart launch iss and launch parameters are not pulled from the url by the fhir client because they are in the hash field and not the query **parameters**

Redirect uri fix

---

src/components/RequestBox/PatientSearchBar/PatientSearchBar.js
src/components/RequestBox/PatientSearchBar/PatientSearchBarStyle.css
src/components/RequestBox/RequestBox.js
src/components/SMARTBox/smart.css

Added search box to patient select view to let the user specify which patient they want.
[REMS-542.](https://jira.mitre.org/browse/REMS-542)

542 patient search

---

How-To-Launch-SMART-on-FHIR-Apps.md

Created Markdown guide for launching several registered SMART on FHIR apps via our Meld sandbox
https://jira.mitre.org/browse/REMS-570
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be …

Create guide on launching SMART on FHIR apps from Meld sandbox

---

src/components/App.js
src/containers/Gateway/Gateway.jsx
src/containers/Gateway/styles.jsx
src/containers/Index.jsx
src/containers/Launch.jsx

Adds a standalone launch page when opening the app on the base url.  When opening `localhost:3000` the app will show a form that allows the user to input the iss/client/scopes before launching.  Inputs default to the value in the env file so if you just want to connect to the regular ehr, you can launch immediately.  
You can test by changing the values in the inputs and seeing that it connects to the chosen ehr.  
There is some room here to connect with the client id registration task and have the dropdown menus include a list of iss/clients, and automatically loading the associated iss/client when you choose the counterpart.
[REMS-573](https://jira.mitre.org/browse/REMS-573)

add standalone launch gateway

---

src/components/RequestBox/RequestBox.js

This PR should be tested with branch  `324-RxStatus` in `pims` ([https://github.com/mcode/pims/pull/58](https://github.com/mcode/pims/pull/58))
- Cleaned up comments  and console log in request generator in relation to RxStatus and NewRx
- Added in MUI "snackbar" for UI notification of RxStatus received (should see this in the bottom left when you hit "send Rx to Pharmacy"
- Validate RxStatus was received by checking the response in the addRx payload in the network tab 
Potential bug noted: Its old, but addRx sends twice? I believe this is an issue we have been aware but wanted to document again. 
[REMS-325](https://jira.mitre.org/browse/REMS-325)
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. …

325 RxStatus

---

src/components/App.js
src/components/RequestBox/InProgressFormBox/InProgressFormBox.js
src/components/RequestBox/RequestBox.js
src/containers/Launch.jsx
src/containers/RequestBuilder.js

Fix deployment to github pages and launch from meld.
Fix crash when sending to rems-admin if rems-admin does not respond.
N/A

Fix deployment to github pages and launch from meld

---

src/containers/RequestBuilder.js
src/util/data.js

This does not necessarily need to be pulled in, but could help address problems with our settings.  One issue we have is that we define the settings in two places, once in data.js as a definition, and then again in the RequestBuilder's state.  This produces the potential for a bug where the values between the two are mismatched, and since the SettingsBox only looks at the headerDefinitions, then tries to set the state, it could end up setting the state for a non-existent value.  This error would not produce an exception and the program would just appear to not work for no reason, making this a dangerous possible error.
The solution is to define one "source of truth" which I've done by pushing the headerDefinitions all into data.js, which RequestBuilder now uses to define its state.  The …

remove potential for uncaught mismatch

---

src/components/SettingsBox/SettingsBox.css
src/components/SettingsBox/SettingsBox.js
src/containers/RequestBuilder.js
src/index.css
src/util/data.js

Pressing the settings button will now open a modal, and the settings panel now saves to localStorage, allowing persistence across sessions for desired settings.
[REMS-577](https://jira.mitre.org/browse/REMS-577)

make settings a modal and add save button

---

src/components/DisplayBox/DisplayBox.js
src/components/SMARTBox/PatientBox.js

For use with the REMS admin PR of the same name, makes suggestion buttons not error out when the card returns with suggestions.

prevent suggestions crash

---

src/components/RequestBox/RequestBox.js
src/components/SettingsBox/SettingsBox.js
src/util/fhir.js

Create the MedicationDispense when sending NewRx. 
Add button to clean up existing MedicationDispenses.
[REMS-609](https://jira.mitre.org/browse/REMS-609)

Create the MedicationDispense when sending NewRx

---

src/components/MedicationStatus/MedicationStatus.jsx
src/components/MedicationStatus/MedicationStatusButton.css
src/components/MedicationStatus/MedicationStatusButton.jsx
src/components/MedicationStatus/MedicationStatusModal.css
src/components/MedicationStatus/MedicationStatusModal.jsx
src/components/RequestBox/PatientSearchBar/PatientSearchBar.js
src/components/RequestBox/RequestBox.js
src/components/SettingsBox/SettingsBox.js
src/containers/RequestBuilder.js
src/index.css

Run alongside https://github.com/mcode/test-ehr/pull/67
Related to https://github.com/mcode/rems-smart-on-fhir/pull/72 but not necessary to pull in to review at same time (uses same UI elements from dev)
* Ported over MedicationDispense check from rems-smart-on-fhir
* Made spacing/styling changes to RequestBuilder.js (nav bar and content below nav bar) 
https://jira.mitre.org/secure/RapidBoard.jspa?rapidView=4984&projectKey=REMS&view=detail&selectedIssue=REMS-5 …

Read dispensed status from ehr

---

src/components/RequestBox/RequestBox.js

I noticed the 'submitted new Rx' snackbar stopped showing up. After looking at it, it seems the state variable that controls opening the snackbar got changed (from open to submittedRx) but the places where the variable was set to true was still setting 'open' and not 'submittedRx'. 
To Test:
Clear out PIMs and send new Rx to pharmacy, should see green snackbar at the bottom saying "Sucess! NewRx received by pharmacy' 
Small bug discovered - no JIRA ticket
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. The …

Update new state variable to open the snackbar as expected

---

src/components/Auth/Login.jsx
src/components/Dashboard/Dashboard.jsx
src/components/Dashboard/ListSelections/EmptySection.jsx
src/components/Dashboard/ListSelections/FormsSection.jsx
src/components/Dashboard/ListSelections/PatientTaskSection.jsx
src/components/Dashboard/styles.jsx
src/components/RequestDashboard/TasksSection.jsx
src/containers/PatientPortal.jsx

- Updated to allow for side panels to be clickable
- Logout button works
- Updated document title to say 'EHR | Patient Portal' 
- Updated icon for questionnaire and added in forms tab with consistent icon
- Display tasks that are assigned to me 
- Added in assign to me and assign to patient functionality and dropdown on request generator
https://jira.mitre.org/browse/REMS-607 and https://jira.mitre.org/browse/REMS-623 
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. The bot will auto assign reviewers to …

623 patient portal task

---

src/components/SMARTBox/PatientBox.js

The multiple requests made was causing an extra option to show up by the MedicationDispense call. After checking with pat, these 3 calls are old and not used anymore. I got rid of the calls so now it displays the options for only the medication requests. 
https://jira.mitre.org/browse/REMS-625 

625 - Remove unused requests causing duplicate options

---

src/components/Dashboard/Dashboard.jsx
src/components/Dashboard/FormElement.jsx
src/components/Dashboard/ListSelections/FormsSection.jsx
src/components/Dashboard/ListSelections/MedicationsSection.jsx
src/components/MedicationStatus/MedicationStatus.jsx
src/components/RequestDashboard/PatientSection.jsx

* Rendered all MedicationDispense.status buttons related to the logged-in patient in the patient portal
* Removed unused code (styles) in request-generator and refactored some code
* Renamed a file (so it matches its parent component)
https://jira.mitre.org/browse/REMS-619
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any …

Patient portal medication status

---

src/util/buildScript.2017071.js

Update to send the rxnorm code to be able to get information on medication for pims new etasu call. Use this with PR in pims for the new etasu call

Update to send rxnorm code

---

src/components/RequestBox/RequestBox.jsx
src/components/SMARTBox/PatientBox.jsx
src/containers/RequestBuilder.jsx
src/util/util.js

Update patient-view hook for medications with the changes to support different REMS admins. This PR fixes patient-view to now be sent and function. It stops short of handling the responses properly from multiple rems-admins. That will require more work and testing and will likely be another ticket.
[REMS-661](https://jira.mitre.org/browse/REMS-661)

Fix patient-view and allow it to work with new rems-admin lookup table.

---

src/components/RequestBox/RequestBox.jsx
src/components/RequestDashboard/SettingsSection.jsx
src/containers/ContextProvider/reducer.js
src/containers/RequestBuilder.jsx
src/util/buildRequest.js
src/util/data.js
src/util/util.js

Handle the returns from patient-view hooks being sent to multiple REMS Administrators.
This should be tested using multiple REMS Administrators.
Please speak to me about how to get this running and tested.
Please include a summary of the changes and the related issue/task. Please also include relevant motivation and context. List any dependencies that are required for this change, including links to other pull requests/branches in other repositories if applicable.
[REMS-674](https://jira.mitre.org/browse/REMS-674)
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled …

Multiple REMS Admins patient-view

---

src/components/EtasuStatus/EtasuStatus.jsx
src/containers/RequestBuilder.jsx
src/util/fhir.js
src/util/util.js

When a medication request contains medicationreference instead of medication codableconcept it doesn't work. We need to handle when the MedicationRequest contains a medicationReference instead of a medicationCodeableConcept. 
Test case:  The Turalio MedicationRequest (pat036-mr-turalio) for Alice Smith (pat036) contains a medicationReference instead of a medicationCodeableConcept.
To Test:
Go through steps as normal for alice smiths's turalio medicaiton. Should see etasu status as expected.
https://jira.mitre.org/browse/REMS-668 
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging …

Update etasu for medication reference

---

src/components/Dashboard/Dashboard.jsx
src/components/Dashboard/ListSelections/NotificationsSection.jsx
src/components/EtasuStatus/EtasuStatus.jsx
src/components/EtasuStatus/EtasuStatusButton.jsx
src/components/EtasuStatus/EtasuStatusComponent.jsx
src/components/EtasuStatus/EtasuStatusModal.jsx
src/containers/RequestBuilder.jsx
src/util/util.js

Fixes issue with auth num
[REMS-670](https://jira.mitre.org/browse/REMS-670)

add auth num

---

src/components/DisplayBox/DisplayBox.jsx

Updated CDS Hooks Card UI based off of mockup styling. 
Old:
Updated:
[REMS-581](https://jira.mitre.org/browse/REMS-581)
- [ x] I have performed a self-review of my code
- [ x] Ensure the target / base branch for any feature PR is set to `dev` not main (the only exception to this is releases from `dev` and hotfix branches)

button updates

---

src/components/EtasuStatus/EtasuStatus.jsx
src/components/RequestBox/RequestBox.jsx
src/util/util.js

Added `?` after fields that are possibly undefined, so when subfields are accessed under those fields, the request-generator doesn't crash. The crashing is caused by trying to access an undefined object or undefined array at index 0. This isn't a code refactoring/overhaul PR, though.
N/A, found randomly while doing https://jira.mitre.org/browse/REMS-712. 
To reproduce: 
* In pims: use Node v21.7.3, checkout `origin/dev`, clear all orders from PIMS. Using …

Resolve TypeError crashes

---

src/components/Dashboard/ListSelections/NotificationsSection.jsx
src/components/EtasuStatus/EtasuStatus.jsx
src/components/EtasuStatus/EtasuStatusComponent.jsx
src/components/RequestBox/PatientSearchBar/PatientSearchBar.jsx
src/components/RequestBox/RequestBox.jsx
src/components/RequestDashboard/SettingsSection.jsx
src/components/RequestDashboard/TasksSection.jsx
src/components/SMARTBox/PatientBox.jsx
src/containers/PatientPortal.jsx
src/util/buildRequest.js
src/util/util.js

In the Task page, the Task component's dropdown menu now has the R4 Practitioner and R4 Patient's names (first/last, first/middle/last) in parentheses, if they exist, in the dropdown options. 
How to observe/manually test:
1. Go to localhost:3000, authenticate
2. Open the Network tab in DevTools
3. Click View Tasks (to see all tasks regardless of patient as the current Practitioner)
4. You will see a GET request for pra1234 done to the test-ehr in the Headers tab, and under the Initiator tab done by TasksSection at line 141.
5. …

REMS-747 Patient portal task assignee string changes

---

src/components/RequestDashboard/SettingsSection.jsx

Add button to delete all Tasks from the EHR
[TASK-762](https://jira.mitre.org/browse/REMS-762)

762 - Add button to delete all Tasks from the EHR

---

src/containers/Index.jsx
src/containers/Launch.jsx

Changes needed to get the request generator to work with the MELD / Logica Sandboxes.
Pull the ISS and launch from the URL.
Default to regular interface (not back office) if realm_role not in login information.
[REMS-767](https://jira.mitre.org/browse/REMS-787)

fix smart launch from MELD sandbox

---

package.json
src/components/App.jsx
vite.config.ts

Changes needed to get the request generator to work with the MELD / Logica Sandboxes.
Build with vite.
Trim the environment variable specifying it is running on GitHub pages to remove spaces.
[REMS-767](https://jira.mitre.org/browse/REMS-787)

Fix environment and vite build

---

src/components/DisplayBox/DisplayBox.jsx

The request generator is not displaying card details in the cards shown on screen.
[REMS-789](https://jira.mitre.org/browse/REMS-789)

show the card details
