mcode/request-generator

src/PrefetchTemplate.js, src/components/ConsoleBox/ConsoleBox.js, src/components/Dashboard/DashboardElement.jsx, src/components/DisplayBox/DisplayBox.js, src/components/Inputs/CheckBox.js, src/components/RequestBox/RequestBox.js, src/components/SMARTBox/PatientBox.js, src/components/SMARTBox/SMARTBox.js, src/components/SettingsBox/SettingsBox.js, src/containers/RequestBuilder.js, src/util/buildRequest.js, src/util/fhir.js
lots of warning fixes, including the error about the missing key in the resource list
=> fix most warnings

.github/pull_request_template.md, .github/workflows/docker-cd-dev.yml, .github/workflows/docker-ci.yml
This PR accomplishes two things: setting up the dev branch for future use by the development team and renaming the master branch to main. Both of these have corresponding ci-cd changes as part of this pull request. There were also some GitHub setting that were modified that effect workflow including branch protection rules, optional auto-merge functionality once the PR gets reviewed, additional requirements for the PR to be up to date with the base branch as well as have all conversations resolved, and finally  branch automatic deletion after PR merge (branches can still be revived and their data and changes are not lost). There is a similar PR set up in mostly all other REMS repositories as well (https://github.com/mcode/pharmacy-information-system/pull/21, …
=> main/dev ci-cd changes

src/components/RequestBox/RequestBox.js, src/containers/RequestBuilder.js
- Added an abort controller to set request timeouts to 10s.
- Cleaned up some console logs
- Reset loading state upon network errors
- https://jira.mitre.org/browse/REMS-283
- https://jira.mitre.org/browse/REMS-283
=> Rems 283 timeout

src/components/RequestBox/RequestBox.js
This PR adds a clear rems admin button to the request generator for use during demos
=> Etasu integration

README.md
Please include a summary of the changes and the related issue/task. Please also include relevant motivation and context. List any dependencies that are required for this change, including links to other pull requests/branches in other repositories if applicable.
=> Rems 384 readme updates

src/components/RequestBox/RequestBox.js, src/containers/RequestBuilder.js, src/properties.json, src/util/data.js
[Add button to launch the smart on fhir app and add the default user and smart app url to the config.
Add buttons to clear the PIMS Database and to Clear the EHR QuestionnaireResponses.
Should be tested with 413-test-ehr-app-launch branch of rems-smart-on-fhir repository.
[REMS-413](https://jira.mitre.org/browse/REMS-413)
=> Launch SMART on FHIR app from Request Generator

src/properties.json
Update request generator to work with version 22.0.1 of Keycloak.
Please test REMS, test-ehr and crd-request-generator together with the Keycloak-upgrade branches.
[REMS-401](https://jira.mitre.org/browse/REMS-401)
=> Keycloak version 22.0.1 support

src/components/DisplayBox/DisplayBox.js, src/components/DisplayBox/card-list.css
Updated display cards to have better styling, use material ui, and be consistent with the smart on fhir cds hooks card. Also fixed the source link to actually open up (didn't open before) in new tab. 
To test (with PR in rems-smart-on-fhir) :
Pull down this branch and rems-smart-on-fhir branch 423-display-card-update. Both display cards should be identical and act similar way. 
https://jira.mitre.org/browse/REMS-423
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. The bot will auto assign reviewers to your …
=> 423 display cards styling update

src/components/DisplayBox/DisplayBox.js
Please include a summary of the changes and the related issue/task. Please also include relevant motivation and context. List any dependencies that are required for this change, including links to other pull requests/branches in other repositories if applicable.
=> notification typo fix

src/components/DisplayBox/DisplayBox.js
Please include a summary of the changes and the related issue/task. Please also include relevant motivation and context. List any dependencies that are required for this change, including links to other pull requests/branches in other repositories if applicable.
=> notification typo fix (#57)

public/index.html, src/PrefetchTemplate.js, src/components/RequestBox/RequestBox.js, src/components/SMARTBox/PatientBox.js, src/util/buildRequest.js
Send the prefetch with the patient-view hook.
[REMS-535](https://jira.mitre.org/browse/REMS-535)
=> Patient view prefetch

.github/workflows/docker-cd-dev.yml, .github/workflows/docker-cd.yml, .github/workflows/docker-ci.yml, .github/workflows/docker-tag-cd.yml
Updates the ci-cd workflow in this branch to better tag each release accordingly. These updates were also forcefully pushed up into each release branch, which was the easiest way to auto tag each of our releases. Checking docker hub now we have tags from 0.1 to 0.13, latest (main), and experimental (dev). The experimental tag will update once this PR gets merged into dev: https://hub.docker.com/repository/docker/codexrems/request-generator/tags?page=1&ordering=last_updated
REMS-491
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are …
=> Update dev to match mains ci-cd workflow 

src/components/SMARTBox/PatientBox.js, src/components/SMARTBox/smart.css
It appears the bugs were fixed with the change in modal and dropdown component.  This PR just updates the CSS to be more readable.  The text was appearing smaller and the patient list needed a couple small changes.
[REMS-522](https://jira.mitre.org/browse/REMS-522)
=> Bug fix dropdown

src/components/SMARTBox/PatientBox.js
Added test-id field to new dropdown to grab that for playwright tests. Test this out with rems-setup add-playwright branch. 
https://jira.mitre.org/browse/REMS-528 
=> add test id to new dropdown for test

src/components/Auth/Login.jsx, src/components/Auth/styles.jsx
Update css of patient portal login page 
To test: go to patient portal and see login page is fixed to look as expected. 
https://jira.mitre.org/browse/REMS-547 
=> Fix styling of patient portal login page

src/components/SMARTBox/PatientBox.js
One line change to have it say 'Select a medication request' instead of 'choose a patient' for the medication request dropdown. 
https://jira.mitre.org/browse/REMS-553 
=> Changed dropdown from 'choose a patient' to 'Select a medication request'

src/components/SMARTBox/PatientBox.js
Updated the "In-progress forms" dropdown options display text to use the Questionnaire.title taken from the Questionnaire resource pointed to by a QuestionnaireResponse.questionnaire. 
Before: 
After: 
https://jira.mitre.org/browse/REMS-548
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review …
=> Update in-progress forms display text

src/PrefetchTemplate.js
Update the patient-view prefetch to include the referenced Medication
Support medicationReference within MedicationRequests.
The MedicationReference for Turalio for Patient Alice Smith now contains a medicationReference instead of a medicationCodeableConcept, please test using this request.
Must be tested with the medication-reference branches of test-ehr, request-generator, rems-admin, and rems-smart-on-fhir.
[REMS-538](https://jira.mitre.org/browse/REMS-538)
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. …
=> Update the patient-view prefetch to include the referenced Medication.

src/containers/Index.jsx, src/containers/Launch.jsx, src/index.css
Made loading text bigger to make more user friendly. 
To test:
Test with update-loading branch of rems-smart-on-fhir. Go to load request generator and see the 'getting client' text bigger in the center of the page.
n/a
=> Update styling of loading page

src/components/RequestBox/PatientSearchBar/PatientSearchBar.jsx
Remove duplicate refresh in request generator 
https://jira.mitre.org/browse/REMS-648
=> Remove duplicate refresh

.env, src/components/RequestDashboard/SettingsSection.jsx, src/containers/RequestBuilder.jsx, src/util/data.js, src/util/util.js
Add encounter start and patient view toggle to settings page. Whichever is selected will send when the user selects a patient from the patient select section. 
If you have encounter-start selected on the toggle, it will hit a 404 until this ticket is done: https://jira.mitre.org/browse/REMS-659 
To Test: 
Toggle between patient view and encounter start, make sure the correct one is sent via networks tab. 
https://jira.mitre.org/browse/REMS-663 
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. The bot will …
=> Setup toggle in settings for encounter start

src/components/DisplayBox/DisplayBox.jsx
Removed code causing DOM element warning and Uncaught TypeError that was breaking the promise that POSTs the Task creation to test-ehr
N/A, this was randomly found post-1.0
Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if …
=> Fix add to task list bug

Dockerfile
=> Docker-cleanup

package-lock.json, package.json
Update vite to 5.4.19 to fix Vite Arbitrary File Read vulnerability (CVE-2025-30208)
=> update vite to 5.4.19

vite.config.ts
=> Vite-update

src/util/buildScript.2017071.js
Get the drug description for the NewRx from the first drug code with a display specified
N/A
=> Get the drug description for the NewRx from the first drug code with a display specified
